apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-post
  template:
    metadata:
      labels:
        app: forum-post
    spec:
      containers:
        - name: forum-post
          image: faiyuching/forum-post
          env:
            - name: MONGO_URI
              value: 'mongodb://forum-post-mongo-srv:27017/forum-post'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: forum-post-srv
spec:
  selector:
    app: forum-post
  ports:
    - name: forum-post
      protocol: TCP
      port: 3000
      targetPort: 3000
