apiVersion: apps/v1
kind: Deployment
metadata:
  name: ionic-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ionic
  template:
    metadata:
      labels:
        app: ionic
    spec:
      containers:
        - name: ionic
          image: faiyuching/ionic
---
apiVersion: v1
kind: Service
metadata:
  name: ionic-srv
spec:
  selector:
    app: ionic
  ports:
    - name: ionic
      protocol: TCP
      port: 3000
      targetPort: 3000
