name: deploy-manifests

on:
  push:
    branches: 
      - main
    paths:
      - 'infra/**'
      - 'infra/k8s-prod/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save zhuoming-info
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
